# -*- coding: utf-8 -*-
"""SENDINFO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkz3Mer0H60ypJITeyroU4tV-x7v3qRL
"""

pip install twilio

import os
from twilio.rest import Client

# Find your Account SID and Auth Token in Account Info and set the environment variables.
# See http://twil.io/secure
account_sid = 'ACeacf9185f6e33c13c6e67286b92c94fb'
auth_token = '8798fdcf18b6c1cb76b968b7bcae1c16'
client = Client(account_sid, auth_token)

message = client.messages.create(
  body='Fire detected',
  from_='+13854753128',
  to='+919789754882'
)

print(message.sid)

